[package]
name = "rain"
version = "0.1.0"
authors = ["Jad Ghalayini <jad.ghalayini@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Parser dependencies
nom = { version = "^5", optional = true }
indexmap = { version = "^1.3.2", optional = true }

[features]
default = ["parser", "prettyprint"]
parser = ["nom", "symbol_table"]
prettyprint = ["symbol_table"]
symbol_table = ["indexmap"]