[package]
name = "rain-lang"
version = "0.0.0"
authors = ["Jad Ghalayini <jad.ghalayini@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "^0.3"
smallvec = "^1.4"
triomphe = "^0.1"
dashmap = "^3"
lazy_static = "^1.4"

# Parser dependencies
nom = { version = "^5", optional = true }
indexmap = { version = "^1.3.2", optional = true }

[dev-dependencies]
pretty_assertions = "^0.6"
rustyline = "^6.1"
clap = "^2.33"

[features]
default = [
    "parser", 
    "prettyprinter"
    ]
parser = ["nom", "symbol_table"]
prettyprinter = ["symbol_table"]
symbol_table = ["indexmap"]

[[example]]
name = "repl"
required-features = ["parser", "prettyprinter"]
